// Console.WriteLine("Привет от ИСп-244");
// Console.WriteLine("Автор: Васильев Юрий");
// Console.WriteLine("Год: 2026");
// int age = 20;
// double gpa = 4.5;
// bool isStudent = true;
// string name = "Юрий";
// Console.WriteLine(name);
// Console.WriteLine(age);
// Console.WriteLine(gpa);
// Console.WriteLine(isStudent);
// var city = "Москва";
// var year = 2026;
// var pi = 3.14159;
// var isActive = true;
// string myName = "Юрий";
// int myAge = 18;
// string myGroup = "ИСП-241";
// Console.WriteLine($"Меня зовут {myName}, мне {myAge} лет, я учусь в группе {myGroup}.");
// Console.Write("Введите ваше имя: ");
// string name2 = Console.ReadLine();
// Console.WriteLine($"Привет, {name2}");
// Console.Write("Введите ваш возраст: ");
// string input = Console.ReadLine();
// int age2 = int.Parse(input);
// Console.WriteLine($"Через 10 лет вам будет {age2 + 10} лет.");
// int x = 10;
// int y = 3;
// Console.WriteLine(x + y);
// Console.WriteLine(x - y);
// Console.WriteLine(x * y);
// Console.WriteLine(x / y);
// Console.WriteLine(x % y);
string firstName = "Юрий";
string lastName = "Васильев";
string firstName = "ИСП-241";
int birthYear = 2008;
double gpa = 4.5;
bool hasScholarship = true;
int currentYear = 2026;
int age = currentYear - birthYear;